### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by d-opri** [d-opri/Capstone-Project#1]
## Show Activity/ History (Read)

As a forgetful person I want to have a list of past bills so that I can check expenses and income

## Description

... (Wireframe, scribble, design or text)

## Acceptance Criteria

- [ ] list Item contains title
- [ ] list Item contains -/+ amount
- [ ] vertical scrolling
- [ ] includes header
- [ ] frame Iphone SE gen 2 (w: 375, h 667)

## Tasks

- [ ] static data for now, inside List Component: 
[
{ “title”: “currywurst”, “amount”:  “- 100.00 $” },
{ “title”: “pizza”, “amount”:  “+ 20.00 $” }
]
- [ ] return listItem prop to List component
- [ ] create function List ( { listItem } ) component
- [ ] return unordered list -> listItems.map(item) -> create list element -> item.title + item.amount
- [ ] add title header
- [ ] styled component List
- [ ] styled component ListItem

## Complexity

XS

**Comment by mbosselmann** [comment]
Hi Danie,
we like your first user story! We have some remarks for you to consider before moving further. Here are our remarks sorted by each section of your user story:

**Value proposition**
- instead of writing forgetful person we recommend to write user as this is the role the forgetful person actually has

**Decription**
- you do not need to add a arrow to indicate vertical scrolling as only actual elements should be shown, you can describe vertical scrolling or show this with a second wireframe

**Acceptance Criteria**
- you do not need to set vertical scrolling as acceptance criteria as this is the default behavior
- the device frame is also not needed as acceptance criteria as you will build a responsive app
- instead of writing one word("title") describe in more detail what you mean with "title"
- currently the criterion "a list of all bills is displayed" is missing, but should be a criterion

**Taks**
- getStaticProps is not needed to fetch the data for list items
- you won't return the list item prop to the list component you hand it over
- instead of creating a list component it may be better to create an activity component that will be used to display every data object

**Complexity**
- as you should decide for yourself if you think how complex the user story is for you, we think it might be that XS underestimates the amount of time
- but that is up to your choice

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by mbosselmann** [comment]
Hi Danie,
great job! 👍 We have one last remark: **Show Activity/ History (Read)** should not replace the title "value proposition", but could be added to the title of your user story (issue) to be more descriptive: "User Story 1: Show Activity/ History (Read)"

And we also have a recommendation for your data structure:
- it might be easier to use numbers for your amounts because you can't do any calculations with strings

After editing your user story, please post the user story again in our thread (should be the last round). :)
